export const headerTemplate = (agentName: string) => `\
# ${agentName} — Generated by Databricks Agent Builder
# Install: pip install databricks-agents mlflow databricks-vectorsearch

import mlflow
from mlflow.pyfunc import ChatModel
from mlflow.types.llm import ChatRequest, ChatResponse, ChatMessage
from databricks.sdk import WorkspaceClient

w = WorkspaceClient()
`;
